name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      # Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Google Cloud Registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/stormmap:latest
            ${{ secrets.GCR_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCR_PROJECT_NAME }}/${{ secrets.GCR_REGISTRY_NAMESPACE }}/stormmap:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}