name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v3
        
      # Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Google Cloud Registry
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCR_REGISTRY_REGION }}-docker.pkg.dev
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/stormmap:latest
            ${{ secrets.GCR_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCR_PROJECT_NAME }}/${{ secrets.GCR_REGISTRY_NAMESPACE }}/stormmap:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCR_ACCESS_TOKEN }}'
      
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'stormmap'
          image: ${{ secrets.GCR_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCR_PROJECT_NAME }}/${{ secrets.GCR_REGISTRY_NAMESPACE }}/stormmap:latest